namespace: default

web:
  image:
    repository: h3poteto/yadockeri-example
    tag: latest
    pullPolicy: Always

  replicaCount: 1
  annotations: {}
  imagePullSecrets: []

  podSecurityContext: {}
  # fsGropup: 200

  securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

  nodeSelector: {}

  tolerations: []

  affinity: {}

  resources:
    requests:
      cpu: 500m
      memory: 1000Mi
    limits:
      memory: 1000Mi

db:
  annotations: {}
  imagePullSecrets: []
  podSecurityContext: {}

  affinity: {}

  tolerations: {}

  resources:
    requests:
      cpu: 500m
      memory: 1000Mi
    limits:
      memory: 1000Mi

service:
  type: ClusterIP
  port: 80
