apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-db-deployment
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Release.Name }}-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-db
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-db
      annotations:
      {{- if .Values.db.annotations }}
        {{- toYaml .Values.db.annotations | nindent 8 }}
      {{- end }}
    spec:
    {{- with .Values.db.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      securityContext:
        {{- toYaml .Values.db.podSecurityContext | nindent 8 }}
      containers:
        - name: postgres
          image: postgres:10.10-alpine
          ports:
            - name: postgres
              containerPort: 5432
              protocol: TCP
          env:
            - name: POSTGRES_DB
              value: yadockeri_example
            - name: POSTGRES_USER
              value: master
            - name: POSTGRES_PASSWORD
              value: docker
    {{- with .Values.db.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.db.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
